server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    function:
      definition: pack|label
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1

logging:
  level:
    inc.evil: debug
    org.zalando.logbook: trace
