apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-dispatcher-service
  labels:
    app: cns-dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cns-dispatcher-service
  template:
    metadata:
      labels:
        app: cns-dispatcher-service
    spec:
      containers:
        - name: cns-dispatcher-service
          image: cns-dispatcher-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://cns-config-service
            - name: SPRING_RABBITMQ_HOST
              value: http://cns-rabbitmq
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ] #Makes Kubernetes wait 5 seconds before sending the SIGTERM signal to the Pod - facilitating graceful shutdown
